// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_URL: PgBouncer/Neon pooler bypass for migrations
    // DATABASE_URL: connection pooler URL for runtime queries
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
